name: Check and Lint

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check-and-lint:
    name: Check and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just
      - name: Run format check
        run: just format-check
      - name: Run lint check
        run: just lint
      - name: Run build check
        run: just build